In [15]:
import numpy as np
from scipy.optimize import minimize

# Input data
age = np.array([30, 35, 40, 45, 50, 55, 60, 65])
ill_people = np.array([19, 27, 38, 48, 61, 73, 84, 91])
people_tested = np.array([100, 100, 100, 100, 100, 100, 100, 100])

# Define the logistic regression function
def logistic_regression(params):
    beta0 = params[0]
    beta1 = params[1]
    logit = beta0 + beta1 * age
    pi = np.exp(logit) / (1 + np.exp(logit))
    log_likelihood = ill_people * np.log(pi) + (people_tested - ill_people) * np.log(1 - pi)
    return -np.sum(log_likelihood)

# Set initial parameter values for optimization
initial_params = np.array([0, 0])

# Perform maximum likelihood estimation (MLE) to find the estimated coefficients
result = minimize(logistic_regression, initial_params, method='Nelder-Mead')
beta_hat_0 = result.x[0]
beta_hat_1 = result.x[1]

# Print the estimated coefficients
print("Estimated coefficient beta_hat_0:", beta_hat_0)
print("Estimated coefficient beta_hat_1:", beta_hat_1)

Estimated coefficient beta_hat_0: -4.682601264693579
Estimated coefficient beta_hat_1: 0.10436184665265441


In [16]:
import math

# Given coefficients
beta0_hat = -5.00
beta1_hat = 0.11

# Input data
age = [30, 35, 40, 45, 50, 55, 60, 65]
ill_people = [19, 27, 38, 48, 61, 73, 84, 91]
people_tested = [100, 100, 100, 100, 100, 100, 100, 100]

# Calculate unbiased estimate and estimated probability for each group
unbiased_estimates = []
estimated_probabilities = []
for i in range(len(age)):
    # Calculate unbiased estimate (number of ill people / number of people tested)
    unbiased_estimate = ill_people[i] / people_tested[i]
    unbiased_estimates.append(unbiased_estimate)

    # Calculate estimated probability using logistic regression equation
    logit = beta0_hat + beta1_hat * age[i]
    probability = math.exp(logit) / (1 + math.exp(logit))
    estimated_probabilities.append(probability)

# Print the unbiased estimates and estimated probabilities for each group
for i in range(len(age)):
    print("Group:", i+1)
    print("Unbiased Estimate:", unbiased_estimates[i])
    print("Estimated Probability:", estimated_probabilities[i])
    print()


Group: 1
Unbiased Estimate: 0.19
Estimated Probability: 0.15446526508353467

Group: 2
Unbiased Estimate: 0.27
Estimated Probability: 0.24048908305088895

Group: 3
Unbiased Estimate: 0.38
Estimated Probability: 0.35434369377420466

Group: 4
Unbiased Estimate: 0.48
Estimated Probability: 0.48750260351578967

Group: 5
Unbiased Estimate: 0.61
Estimated Probability: 0.6224593312018546

Group: 6
Unbiased Estimate: 0.73
Estimated Probability: 0.740774899182154

Group: 7
Unbiased Estimate: 0.84
Estimated Probability: 0.8320183851339245

Group: 8
Unbiased Estimate: 0.91
Estimated Probability: 0.8956687768809988



#manual epochs

In [17]:
import numpy as np

# Input data
age = np.array([30, 35, 40, 45, 50, 55, 60, 65])
ill_people = np.array([19, 27, 38, 48, 61, 73, 84, 91])
people_tested = np.array([100, 100, 100, 100, 100, 100, 100, 100])

# Initialize coefficients
beta0_hat = 0
beta1_hat = 0

# Set learning rate and number of epochs
learning_rate = 0.001
num_epochs = 20000

# Perform gradient descent
for epoch in range(num_epochs):
    # Calculate predicted probabilities
    pi = np.exp(beta0_hat + beta1_hat * age) / (1 + np.exp(beta0_hat + beta1_hat * age))
    
    # Update coefficients using gradient descent
    beta0_hat -= learning_rate * np.sum((pi - ill_people/people_tested))
    beta1_hat -= learning_rate * np.sum((pi - ill_people/people_tested) * age)

# Print the estimated coefficients
print("Estimated coefficient beta_hat_0:", beta0_hat)
print("Estimated coefficient beta_hat_1:", beta1_hat)


Estimated coefficient beta_hat_0: -5.98753193963521
Estimated coefficient beta_hat_1: 0.10912229500138065


ques 1 and 2 through manual epochs


In [18]:
import numpy as np

# Input data
age = np.array([30, 35, 40, 45, 50, 55, 60, 65])
ill_people = np.array([19, 27, 38, 48, 61, 73, 84, 91])
people_tested = np.array([100, 100, 100, 100, 100, 100, 100, 100])

# Initialize coefficients
beta0_hat = 0
beta1_hat = 0

# Set learning rate and number of epochs
learning_rate = 0.001
num_epochs = 20000

# Perform gradient descent
for epoch in range(num_epochs):
    # Calculate predicted probabilities
    pi = np.exp(beta0_hat + beta1_hat * age) / (1 + np.exp(beta0_hat + beta1_hat * age))
    
    # Update coefficients using gradient descent
    beta0_hat -= learning_rate * np.sum((pi - ill_people/people_tested))
    beta1_hat -= learning_rate * np.sum((pi - ill_people/people_tested) * age)

print(beta0_hat)
print(beta1_hat)
# Calculate unbiased estimate for each group
unbiased_estimates = ill_people / people_tested

# Calculate estimated probability for each group
estimated_probabilities = np.exp(beta0_hat + beta1_hat * age) / (1 + np.exp(beta0_hat + beta1_hat * age))

# Print the unbiased estimates and estimated probabilities for each group
for i in range(len(age)):
    print("Group:", i+1)
    print("Unbiased Estimate:", unbiased_estimates[i])
    print("Estimated Probability:", estimated_probabilities[i])
    print()


-5.98753193963521
0.10912229500138065
Group: 1
Unbiased Estimate: 0.19
Estimated Probability: 0.06216026601222806

Group: 2
Unbiased Estimate: 0.27
Estimated Probability: 0.1026379538534821

Group: 3
Unbiased Estimate: 0.38
Estimated Probability: 0.16484108444091122

Group: 4
Unbiased Estimate: 0.48
Estimated Probability: 0.25406872603004454

Group: 5
Unbiased Estimate: 0.61
Estimated Probability: 0.37018641176440514

Group: 6
Unbiased Estimate: 0.73
Estimated Probability: 0.5035485117815373

Group: 7
Unbiased Estimate: 0.84
Estimated Probability: 0.6364075958060569

Group: 8
Unbiased Estimate: 0.91
Estimated Probability: 0.7512737556472597



In [18]:
import numpy as np

# Input data
age = np.array([30, 35, 40, 45, 50, 55, 60, 65])
ill_people = np.array([19, 27, 38, 48, 61, 73, 84, 91])
people_tested = np.array([100, 100, 100, 100, 100, 100, 100, 100])

# Initialize coefficients
beta0_hat = 0
beta1_hat = 0

# Set learning rate and number of epochs
learning_rate = 0.05
num_epochs = 5

# Perform gradient descent
for epoch in range(num_epochs):
    # Calculate predicted probabilities
    pi = np.exp(beta0_hat + beta1_hat * age) / (1 + np.exp(beta0_hat + beta1_hat * age))
    
    # Update coefficients using gradient descent
    beta0_hat -= learning_rate * np.sum((pi - ill_people/people_tested))
    beta1_hat -= learning_rate * np.sum((pi - ill_people/people_tested) * age)

# Calculate unbiased estimate for each group
unbiased_estimates = ill_people / people_tested

# Calculate estimated probability for each group
estimated_probabilities = np.exp((-5.00) + ((0.11) * age)) / (1 + np.exp((-5.0) + ((0.11) * age)))

# Print the unbiased estimates and estimated probabilities for each group
for i in range(len(age)):
    print("Group:", i+1)
    print("Unbiased Estimate:", unbiased_estimates[i])
    print("Estimated Probability:", estimated_probabilities[i])
    print()


Group: 1
Unbiased Estimate: 0.19
Estimated Probability: 0.15446526508353467

Group: 2
Unbiased Estimate: 0.27
Estimated Probability: 0.24048908305088895

Group: 3
Unbiased Estimate: 0.38
Estimated Probability: 0.35434369377420466

Group: 4
Unbiased Estimate: 0.48
Estimated Probability: 0.48750260351578967

Group: 5
Unbiased Estimate: 0.61
Estimated Probability: 0.6224593312018546

Group: 6
Unbiased Estimate: 0.73
Estimated Probability: 0.740774899182154

Group: 7
Unbiased Estimate: 0.84
Estimated Probability: 0.8320183851339245

Group: 8
Unbiased Estimate: 0.91
Estimated Probability: 0.8956687768809988



In [20]:
import numpy as np

age = np.array([30, 35, 40, 45, 50, 55, 60, 65])

# Add a column of ones for the intercept term
X = np.column_stack((np.ones(len(age)), age))
print(X)

[[ 1. 30.]
 [ 1. 35.]
 [ 1. 40.]
 [ 1. 45.]
 [ 1. 50.]
 [ 1. 55.]
 [ 1. 60.]
 [ 1. 65.]]


ques 1 and 2 through manual epochs


In [1]:
import numpy as np
import statsmodels.api as sm

# Define the age values and the corresponding number of ill and tested people
age = np.array([30, 35, 40, 45, 50, 55, 60, 65])
ill_people = np.array([19, 27, 38, 48, 61, 73, 84, 91])
tested_people = np.array([100, 100, 100, 100, 100, 100, 100, 100])

# Normalize the dependent variable to be in the unit interval
normalized_illness_rate = ill_people / tested_people

# Create a matrix X with the age values
X = sm.add_constant(age)  # Add a column of ones for the intercept term

# Perform logistic regression to estimate the coefficients β̂0 and β̂1
model = sm.Logit(normalized_illness_rate, X)
results = model.fit()
estimated_coefficients = results.params

# Compute the covariance matrix for β̂ using the formula Var(β̂) = (X'WX)^(-1)
covariance_matrix = np.linalg.inv(np.dot(np.dot(X.T, np.diag(normalized_illness_rate * (1 - normalized_illness_rate))), X))

# Print the estimated coefficients and covariance matrix
print("Estimated Coefficients:")
print(estimated_coefficients)
print("\nCovariance Matrix for β̂:")
print(covariance_matrix)
print(X)


Optimization terminated successfully.
         Current function value: 0.463573
         Iterations 6
Estimated Coefficients:
[-4.68261047  0.10436217]

Covariance Matrix for β̂:
[[ 1.49491300e+01 -3.10959606e-01]
 [-3.10959606e-01  6.77290872e-03]]
[[ 1. 30.]
 [ 1. 35.]
 [ 1. 40.]
 [ 1. 45.]
 [ 1. 50.]
 [ 1. 55.]
 [ 1. 60.]
 [ 1. 65.]]


In [ ]:
covariance_matrix = np.linalg.inv(np.dot(np.dot(X.T, np.diag(normalized_illness_rate * (1 - normalized_illness_rate))), X))

In [23]:
normalized_illness_rate

array([0.19, 0.27, 0.38, 0.48, 0.61, 0.73, 0.84, 0.91])

In [3]:
(normalized_illness_rate * (1 - normalized_illness_rate))

array([0.1539, 0.1971, 0.2356, 0.2496, 0.2379, 0.1971, 0.1344, 0.0819])

In [4]:
np.diag(normalized_illness_rate * (1 - normalized_illness_rate))

array([[0.1539, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.1971, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.2356, 0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.2496, 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.2379, 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 0.1971, 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.1344, 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.0819]])

In [5]:
X.T

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [30., 35., 40., 45., 50., 55., 60., 65.]])

In [6]:
np.dot(X.T, np.diag(normalized_illness_rate * (1 - normalized_illness_rate)))

array([[ 0.1539,  0.1971,  0.2356,  0.2496,  0.2379,  0.1971,  0.1344,
         0.0819],
       [ 4.617 ,  6.8985,  9.424 , 11.232 , 11.895 , 10.8405,  8.064 ,
         5.3235]])

In [7]:
X

array([[ 1., 30.],
       [ 1., 35.],
       [ 1., 40.],
       [ 1., 45.],
       [ 1., 50.],
       [ 1., 55.],
       [ 1., 60.],
       [ 1., 65.]])

In [ ]:
np.dot(np.dot(X.T, np.diag(normalized_illness_rate * (1 - normalized_illness_rate))), X)

In [9]:
import numpy as np

# Define the data
dose = np.array([49.057, 52.991, 56.991, 60.542, 64.359, 68.891, 72.611, 76.542])
z = np.array([3.893, 3.970, 4.043, 4.103, 4.164, 4.233, 4.258, 4.338])
number_killed = np.array([6, 13, 18, 28, 52, 53, 61, 60])
number_survival = np.array([53, 47, 44, 28, 11, 6, 1, 0])

# Calculate the unbiased estimate for each group
unbiased_estimate_group = (number_killed) / (number_killed + number_survival)

# Print the unbiased estimate for each group
for i in range(len(dose)):
    print(f"Group {i+1}: Unbiased Estimate = {unbiased_estimate_group[i]}")


Group 1: Unbiased Estimate = 0.1016949152542373
Group 2: Unbiased Estimate = 0.21666666666666667
Group 3: Unbiased Estimate = 0.2903225806451613
Group 4: Unbiased Estimate = 0.5
Group 5: Unbiased Estimate = 0.8253968253968254
Group 6: Unbiased Estimate = 0.8983050847457628
Group 7: Unbiased Estimate = 0.9838709677419355
Group 8: Unbiased Estimate = 1.0


In [10]:
import numpy as np

# Define the data
dose = np.array([49.057, 52.991, 56.991, 60.542, 64.359, 68.891, 72.611, 76.542])
z = np.array([3.893, 3.970, 4.043, 4.103, 4.164, 4.233, 4.258, 4.338])
number_killed = np.array([6, 13, 18, 28, 52, 53, 61, 60])
number_survival = np.array([53, 47, 44, 28, 11, 6, 1, 0])

# Calculate the empirical logit for each group
empirical_logit_group = np.log(number_killed / number_survival)

# Print the empirical logit for each group
for i in range(len(dose)):
    print(f"Group {i+1}: Empirical Logit = {empirical_logit_group[i]}")


Group 1: Empirical Logit = -2.178532444324067
Group 2: Empirical Logit = -1.285198244248522
Group 3: Empirical Logit = -0.8938178760220964
Group 4: Empirical Logit = 0.0
Group 5: Empirical Logit = 1.5533484457830569
Group 6: Empirical Logit = 2.178532444324067
Group 7: Empirical Logit = 4.110873864173311
Group 8: Empirical Logit = inf


C:\Users\user\AppData\Local\Temp\ipykernel_8732\3300235719.py:10: RuntimeWarning: divide by zero encountered in true_divide
  empirical_logit_group = np.log(number_killed / number_survival)


In [50]:
import numpy as np

# Data
age = np.array([30, 35, 40, 45, 50, 55, 60, 65])
number_ill = np.array([19, 27, 38, 48, 61, 73, 84, 91])
number_tested = np.array([100, 100, 100, 100, 100, 100, 100, 100])
beta0 = -5
beta1 = 0.11
n = 100
# Unbiased estimate
unbiased_estimate = number_ill / number_tested

# Estimated probability
pi_i = np.exp(beta0 + (beta1 * age)) / (1 + np.exp(beta0 + (beta1 * age)))

# Covariance matrix for beta_hat
X = np.column_stack((np.ones_like(age), age))
V = np.diag(n*pi_i * (1 - pi_i))
cov_beta_hat = np.linalg.inv(np.dot(np.dot(np.transpose(X),V),X))

# Print the results
print("Unbiased Estimate (pi):", unbiased_estimate)
print("Estimated Probability (pi_i):", pi_i)
print("Covariance Matrix for beta_hat:")
print(cov_beta_hat)
# print(X)
# print(V)




Unbiased Estimate (pi): [0.19 0.27 0.38 0.48 0.61 0.73 0.84 0.91]
Estimated Probability (pi_i): [0.15446527 0.24048908 0.35434369 0.4875026  0.62245933 0.7407749
 0.83201839 0.89566878]
Covariance Matrix for beta_hat:
[[ 1.56680648e-01 -3.22362785e-03]
 [-3.22362785e-03  6.93736869e-05]]


In [43]:
X

array([[ 1, 30],
       [ 1, 35],
       [ 1, 40],
       [ 1, 45],
       [ 1, 50],
       [ 1, 55],
       [ 1, 60],
       [ 1, 65]])

In [31]:
import numpy as np
from scipy.stats import logistic

dose = np.array([49.057, 52.991, 56.991, 60.542, 64.359, 68.891, 72.611, 76.542])
z = np.log(dose)  # Taking the natural logarithm of dose

number_killed = np.array([6, 13, 18, 28, 52, 53, 61, 60])
number_survival = np.array([53, 47, 44, 28, 11, 6, 1, 0])

# Coefficient values
Beta_0 = -60.717
Beta_1 = 14.883

# Calculate the estimated probabilities (pi_hat)
linear_combination = Beta_0 + Beta_1 * z
estimated_probabilities = np.exp(linear_combination) / (1 + np.exp(linear_combination))

# Calculate the covariance matrix for beta_hat
X = np.column_stack((np.ones(len(z)), z))
n = len(X)

# Calculate the diagonal matrix of pi_hat * (1 - pi_hat)
V = np.diag(estimated_probabilities * (1 - estimated_probabilities))

# Calculate the covariance matrix
covariance_matrix = np.linalg.inv(np.dot(np.dot(X.T, V), X))

print("Estimated probabilities (pi_hat):")
print(estimated_probabilities)
print("\nCovariance matrix for beta_hat:")
print(covariance_matrix)


Estimated probabilities (pi_hat):
[0.05853922 0.16387517 0.36664939 0.58733752 0.77952629 0.90684254
 0.95514327 0.97902173]

Covariance matrix for beta_hat:
[[1640.86098478 -400.61296479]
 [-400.61296479   97.86932763]]


In [36]:
import numpy as np

# Data
# age = np.array([30, 35, 40, 45, 50, 55, 60, 65])
# number_ill = np.array([19, 27, 38, 48, 61, 73, 84, 91])
# number_tested = np.array([100, 100, 100, 100, 100, 100, 100, 100])
dose = np.array([49.057, 52.991, 56.991, 60.542, 64.359, 68.891, 72.611, 76.542])
z = np.array([3.893, 3.970, 4.043, 4.103, 4.164, 4.233, 4.258, 4.338])
beta0 = -60.717
beta1 = 14.883

# Unbiased estimate
# unbiased_estimate = number_ill / number_tested

# Estimated probability
pi_i = np.exp(beta0 + beta1 * z) / (1 + np.exp(beta0 + beta1 * z))

# Covariance matrix for beta_hat
X = np.column_stack((np.ones_like(dose), dose))
V = np.diag(pi_i * (1 - pi_i))
cov_beta_hat = np.linalg.inv(X.T @ V @ X)

# Print the results
print("Unbiased Estimate (pi):", unbiased_estimate)
print("Estimated Probability (pi_i):", pi_i)
print("Covariance Matrix for beta_hat:")
print(cov_beta_hat)


Unbiased Estimate (pi): [0.19 0.27 0.38 0.48 0.61 0.73 0.84 0.91]
Estimated Probability (pi_i): [0.05855326 0.16362635 0.36701802 0.58612013 0.77830432 0.90743737
 0.93430708 0.9790707 ]
Covariance Matrix for beta_hat:
[[ 9.11881365e+01 -1.49130768e+00]
 [-1.49130768e+00  2.46581093e-02]]


In [38]:
import numpy as np

number_killed = np.array([6, 13, 18, 28, 52, 53, 61, 60])
number_survival = np.array([53, 47, 44, 28, 11, 6, 1, 0])
pi_i = number_killed / (number_killed + number_survival)
z = np.array([3.893, 3.970, 4.043, 4.103, 4.164, 4.233, 4.258, 4.338])

# Compute V11
V11 = np.sum(number_killed * pi_i * (1 - pi_i))

# Compute V22
V22 = np.sum(number_killed * pi_i * (1 - pi_i) * z**2)

# Construct the observed Fisher information matrix V
V = np.diag([V11, V22])

print("Observed Fisher Information Matrix V:")
print(V)


Observed Fisher Information Matrix V:
[[ 26.76693743   0.        ]
 [  0.         455.7894148 ]]


In [45]:
#HWM3
import numpy as np
from scipy.special import factorial
import matplotlib.pyplot as plt
from scipy.stats import chi2

####DATA
#Variables
age = np.array([30,35,40,45,50,55,60,65])
of_ill_people = np.array([19,27,38,48,61,73,84,91])
of_people_tested =np.array([100,100,100,100,100,100,100,100])

Z = age #we put Z=log(age)
π_i = pi_i_function(Z)


#Parameters
beta0_h = -5
beta1_h = 0.11
alpha = 0.05

#function:π_i(x_i)
def pi_i_function(x_i):
    num = np.exp(beta0_h+beta1_h*x_i)
    den = 1 + np.exp(beta0_h+beta1_h*x_i)
    return (num/den)


n=100
T=np.transpose(np.array([[1,1,1,1,1,1,1,1],Z]))
V=np.diag(n*π_i*(1-π_i))
covariance_matrix=np.linalg.inv(np.dot(np.dot(np.transpose(T),V),T))

print(covariance_matrix)


[[ 1.56680648e-01 -3.22362785e-03]
 [-3.22362785e-03  6.93736869e-05]]


In [49]:
question:4

beta0=-6
chi2_Q4 = ((beta0_h - beta0)**2)/covariance_matrix[0][0] # = 0.034
df = 1
alpha = 0.05
critical_value_Q4 = chi2.ppf(1 - alpha, df)

print(chi2_Q4)
print(critical_value_Q4)



6.382409123767618
3.841458820694124


In [58]:
beta1=0.2
chi2_Q5 = ((beta1_h - beta1)**2)/covariance_matrix[1][1] # = 0.004
df = 1
alpha = 0.05
critical_value_Q5= chi2.ppf(1 - alpha, df) 

print(chi2_Q5)
print(critical_value_Q5)

116.75896671998848
3.841458820694124


In [65]:
#option 1 : var(beta0 + 50*beta1) =  var(beta0) + var(50*beta1) + 2*cov(beta0,50*beta1)
variance1 = covariance_matrix[0][0] + (50**2)*covariance_matrix[1][1] + 2*50*covariance_matrix[0][1]
#option 2 : var(beta0 + 50*beta1) = D*cov(beta)*D' with D = (1,50) and beta = (beta0,beta1)
#Because : beta0 + 50*beta1 = (1,50)*(beta0,beta1)'
D = np.array([1,50])
variance2 = np.dot(np.dot(D,covariance_matrix),np.transpose(D)) # = 4216.253
print(covariance_matrix)
chi2_Q6 = ((beta0_h + 50*beta1_h)**2)/variance2 #(=32.25)
alpha = 0.05
critical_value_Q6 = chi2.ppf(1 - alpha, 2) #(=5.99<chi2_Q6)
print((beta0_h + 50*beta1_h)**2)
print(variance1)
print(chi2_Q6)
print(critical_value_Q6)

[[ 1.56680648e-01 -3.22362785e-03]
 [-3.22362785e-03  6.93736869e-05]]
0.25
0.007752080250000015
32.24940815079917
5.991464547107979


In [68]:
xi = of_ill_people
ni=100

#underH1:
beta0_h,beta1_h = -5,0.11
S1= np.sum( np.log(factorial(ni)/factorial(xi)) - np.log(factorial(ni-xi))+beta0_h*np.sum(xi))
S2=beta1_h*np.sum(xi*Z) - np.sum(ni*np.log(1+np.exp(beta0_h + beta1_h*Z)))
undH1 = S1+S2
#underH0
beta0,beta1 = -5.50,0.15
S1= np.sum( np.log(factorial(ni)/factorial(xi)) - np.log(ni-xi)+beta0*np.sum(xi))
S2=beta1*np.sum(xi*Z) - np.sum(ni*np.log(1+np.exp(beta0 + beta1*Z)))
undH0 = S1+S2

#deviance
deviance = -2*(undH1-undH0)
print(undH1)
print(undH0)
print(deviance)

-15454.899814914304
-16047.864049472711
-1185.928469116814


In [73]:
##7version2

#undH0
beta0_h,beta1_h = -5.5 , 0.15
π_i = pi_i_function(Z)

S11=np.sum(np.log(factorial(n))-np.log(factorial(xi)) - np.log(factorial(ni-xi)) )
S22=np.sum(xi*np.log(π_i))
S33=np.sum((ni-xi)*np.log(1-π_i))

und0 = S11 +S22 +S33

#undH1
beta0_h,beta1_h = -5,0.11
π_i = pi_i_function(Z)

S11=np.sum(np.log(factorial(n))-np.log(factorial(xi)) - np.log(factorial(ni-xi)) )
S22=np.sum(xi*np.log(π_i))
S33=np.sum((ni-xi)*np.log(1-π_i))

und1 = S11 +S22 +S33

deviance = -2*(und1-und0)

print(S11)
print(S22)
print(und0)
print(und1)
print(deviance)
print(xi)

423.1536869626002
-224.17314168317904
-129.89797785468403
-19.899814914303192
-219.99632588076167
[19 27 38 48 61 73 84 91]
